### PR TITLE
Added private api's for using real icons

### PR DESCRIPTION
**Pull request by AndreasVerhoeven**

### CODE REVIEW

**Comment by AndreasVerhoeven** [comment]
I knew UIActivityViewController does run in the process within UIKit and has access to a list of apps supporting file types and shows their icons. Putting a breakpoint on UIActivityViewController and reading the disassembly pointed me to _UIActivityApplicationHelper, which in turn pointed me to LSApplicationProxy.  LS is short for "Launch Services", so that had to be something close. 

Digging around in MobileServices.framework, i saw LSApplicationWorkspace, which had to be similar to OSX' NSWorkspace: https://github.com/JaviSoto/iOS8-Runtime-Headers/blob/master/Frameworks/MobileCoreServices.framework/LSApplicationWorkspace.h

**Comment by gabrielribeiro** [comment]
So, it may work with real icons? Awesome! Can it replace e entirely lock screen? 

## 

Gabriel Ribeiro / Gerente de Projetos
19 9 9676 3137 / gribeiro@mobirama.com.br

Mobirama Mobile Solutions 
Campinas, SP
http://www.mobirama.com.br

**Comment by AndreasVerhoeven** [comment]
This pull-request does work with real-icons. It can't replace the lock screen: it's a demo/prototype.

**Comment by dknk** [comment]
First: Great work!
But I'm new with programming, and could you , please, help with installation steps(IOS 7.1.2(Iphone 4s) or IOS 8(Ipad mini) ?

Kind regards,

**Comment by iAlborz** [comment]
Hi. i'm a UX/UI designer, and want to contribute to the development going on here.
what would be the best way to stay in touch?

**Comment by lmmenge** [comment]
@iAlborz I guess creating new issues for suggestions in this GitHub is a start. However, I really have to stress this out: right now, this is a play project. No deadlines, no guarantees it'll get somewhere. Again: the idea was to recreate Michael Steeber's mockup in real life.

There are major hurdles to overcome before this even dreams of becoming something: (Proper icons, proper launch screenshots, and ultimately, the fact that this will never go into the App Store due to the rules and it could only ever be adapted to be useful if it gets converted by someone into a jailbreak tweak to replace the homescreen (or at least extend upon the homescreen binary). I have no idea what would be needed to "replace" the homescreen on iOS.

**Pull request merged**
